FROM node:latest

WORKDIR /src

COPY . /src



# RUN node bin/www

EXPOSE 3000
# RUN apt-get install nodejs -y && \
#     cd ~/src && npm install && \
#         npm run



CMD [ "node","src/bin/www" ]